# Generated by Django 3.1.6 on 2021-02-17 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_course', models.CharField(max_length=120, verbose_name='Ders')),
                ('exam_title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('start_date', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('deadline_date', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('assigned_students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Yayınlayan')),
            ],
            options={
                'ordering': ['publishing_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField(verbose_name='Soru İçeriği')),
                ('option_1', models.TextField(verbose_name='Soru Şıkkı 1')),
                ('option_2', models.TextField(verbose_name='Soru Şıkkı 2')),
                ('option_3', models.TextField(verbose_name='Soru Şıkkı 3')),
                ('option_4', models.TextField(verbose_name='Soru Şıkkı 4')),
                ('right_option', models.IntegerField(verbose_name='Doğru Şık')),
                ('belonged_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belonged_exam', to='exam.exam')),
            ],
            options={
                'ordering': ['belonged_exam', 'id'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(to='exam.Question'),
        ),
    ]
